# Generated by Django 5.0.6 on 2025-06-12 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JumbotronSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gambar untuk slide jumbotron', upload_to='jumbotron_slides/')),
                ('title', models.CharField(blank=True, help_text='Judul besar di slide (opsional)', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Sub-judul di slide (opsional)', max_length=300)),
                ('link_url', models.URLField(blank=True, help_text='Link yang terkait dengan slide (opsional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan slide')),
                ('is_active', models.BooleanField(default=True, help_text='Apakah slide ini aktif dan ditampilkan?')),
            ],
            options={
                'verbose_name': 'Slide Jumbotron',
                'verbose_name_plural': 'Slide Jumbotron',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KetuaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama Ketua IMM FTIK UMKO', max_length=200)),
                ('photo', models.ImageField(help_text='Foto Ketua', upload_to='ketua_photos/')),
                ('welcome_message', models.TextField(help_text='Kata sambutan Ketua')),
                ('is_active', models.BooleanField(default=True, help_text='Apakah info Ketua ini aktif?')),
            ],
            options={
                'verbose_name': 'Info Ketua',
                'verbose_name_plural': 'Info Ketua',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Teks yang akan ditampilkan di navigasi', max_length=100)),
                ('url_name', models.CharField(blank=True, help_text="URL name Django (misal: 'home', 'pendaftaran', 'chatbot_app:home')", max_length=200, null=True)),
                ('custom_url', models.URLField(blank=True, help_text="URL kustom jika tidak menggunakan URL name Django (misal: 'https://example.com')", null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampilan di navigasi')),
                ('is_active', models.BooleanField(default=True, help_text='Apakah item navigasi ini aktif?')),
            ],
            options={
                'verbose_name': 'Item Navigasi',
                'verbose_name_plural': 'Item Navigasi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul Berita', max_length=255)),
                ('slug', models.SlugField(help_text='Slug untuk URL berita (otomatis terisi)', unique=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Gambar kecil/thumbnail berita', null=True, upload_to='news_thumbnails/')),
                ('content', models.TextField(help_text='Isi berita lengkap')),
                ('publish_date', models.DateTimeField(auto_now_add=True, help_text='Tanggal publikasi')),
                ('is_published', models.BooleanField(default=True, help_text='Apakah berita ini sudah dipublikasikan?')),
            ],
            options={
                'verbose_name': 'Berita Ikatan',
                'verbose_name_plural': 'Berita Ikatan',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='IMM FTIK UMKO', help_text='Nama situs utama (misal: IMM FTIK UMKO)', max_length=200)),
                ('total_kader_count', models.PositiveIntegerField(default=0, help_text='Jumlah total Kader IMM FTIK UMKO')),
                ('footer_text', models.TextField(blank=True, help_text='Teks singkat di footer')),
                ('copyright_text', models.CharField(default='© 2025 IMM FTIK UMKO. All rights reserved.', help_text='Teks Copyright di footer', max_length=200)),
            ],
            options={
                'verbose_name': 'Pengaturan Situs',
                'verbose_name_plural': 'Pengaturan Situs',
            },
        ),
        migrations.AddConstraint(
            model_name='ketuainfo',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_ketua_info'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Jika ini adalah sub-menu dari menu lain', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Tampilanutama_app.menuitem'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Penulis berita', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='siteconfiguration',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_site_configuration'),
        ),
    ]
