# Generated by Django 5.0.6 on 2025-06-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Logo situs (opsional)', null=True, upload_to='site_logos/'),
        ),
    ]
