# Generated by Django 5.0.6 on 2025-06-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0003_topbarconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_text',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alamat Sekretariat di Footer'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Kontak di Footer'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon Kontak di Footer'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_website',
            field=models.URLField(blank=True, null=True, verbose_name='Website di Footer (contoh: https://domain.com)'),
        ),
    ]
