# Generated by Django 5.0.1 on 2025-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0004_remove_siteconfiguration_footer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiMisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Visi - Misi', max_length=200, verbose_name='Judul Halaman')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='visimisi/', verbose_name='Logo Perusahaan/Organisasi')),
                ('subtitle', models.CharField(blank=True, help_text='Contoh: AHU-0066022-AH.01.14 Tahun 2021', max_length=200, null=True, verbose_name='Teks di Bawah Logo')),
                ('visi_title', models.CharField(default='VISI', max_length=50, verbose_name='Judul Kolom Visi')),
                ('visi_content', models.TextField(verbose_name='Isi Visi')),
                ('misi_title', models.CharField(default='MISI', max_length=50, verbose_name='Judul Kolom Misi')),
                ('misi_content', models.TextField(help_text='Untuk membuat daftar berpoin, gunakan tanda hubung (-) atau angka (1.) dan tekan Enter untuk setiap poin baru.', verbose_name='Isi Misi')),
            ],
            options={
                'verbose_name': 'Halaman Visi & Misi',
                'verbose_name_plural': 'Halaman Visi & Misi',
            },
        ),
    ]
