# Generated by Django 5.0.6 on 2025-06-29 09:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0005_visimisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('position', models.CharField(max_length=200, verbose_name='Jabatan (contoh: Ketua Umum, Sekretaris Bidang Organisasi)')),
                ('period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Periode Jabatan (contoh: 2023-2024)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='organization_members/', verbose_name='Foto Anggota')),
                ('bio_or_description', models.TextField(blank=True, help_text='Opsional: Biografi singkat atau deskripsi tugas anggota.', null=True, verbose_name='Biografi Singkat/Deskripsi Tugas')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampilan di halaman struktur organisasi. Angka lebih kecil akan tampil duluan.')),
                ('is_active', models.BooleanField(default=True, help_text='Centang jika anggota ini ingin ditampilkan di halaman struktur organisasi.', verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Anggota Struktur Organisasi',
                'verbose_name_plural': 'Anggota Struktur Organisasi',
                'ordering': ['order', 'position', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=tinymce.models.HTMLField(help_text='Isi berita lengkap'),
        ),
        migrations.AlterField(
            model_name='visimisi',
            name='misi_content',
            field=tinymce.models.HTMLField(verbose_name='Isi Misi'),
        ),
        migrations.AlterField(
            model_name='visimisi',
            name='visi_content',
            field=tinymce.models.HTMLField(verbose_name='Isi Visi'),
        ),
    ]
