# Generated by Django 5.0.6 on 2025-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0006_organizationmember_alter_newsarticle_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'ordering': ['category', 'order', 'position', 'name'], 'verbose_name': 'Anggota Struktur Organisasi', 'verbose_name_plural': 'Anggota Struktur Organisasi'},
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='category',
            field=models.CharField(choices=[('Pimpinan Harian', 'Pimpinan Harian Komisiariat'), ('Bidang Organisasi', 'Bidang Organisasi'), ('Bidang Sosial Pemberdayaan Masyarakat', 'Bidang Sosial Pemberdayaan Masyarakat'), ('Bidang DPM', 'Bidang DPM'), ('Bidang Seni Budaya Olahraga', 'Bidang Seni Budaya Olahraga'), ('Bidang SBO', 'Bidang SBO'), ('Bidang IMMawati', 'Bidang IMMawati'), ('Bidang IMMawan', 'Bidang IMMawan'), ('Bidang KADER', 'Bidang KADER'), ('Bidang Kewirausahaan dan Eksternal', 'Bidang Kewirausahaan dan Eksternal'), ('Bidang FAIKRIK', 'Bidang FAIKRIK'), ('Bidang KPPK', 'Bidang KPPK'), ('Bidang PKM', 'Bidang PKM'), ('Bidang Komunikasi', 'Bidang Komunikasi'), ('Bidang Tadbigh', 'Bidang Tadbigh'), ('Bidang BPK', 'Bidang BPK')], default='Pimpinan Harian', max_length=100, verbose_name='Kategori Anggota'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Urutan tampilan di halaman struktur organisasi dalam kategori yang sama. Angka lebih kecil akan tampil duluan.'),
        ),
    ]
