# Generated by Django 5.0.6 on 2025-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0007_alter_organizationmember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'ordering': ['leadership_type', 'division', 'order', 'name'], 'verbose_name': 'Anggota Struktur Organisasi', 'verbose_name_plural': 'Anggota Struktur Organisasi'},
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='category',
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='division',
            field=models.CharField(choices=[('None', 'None (Untuk Ketua/Sekum/Bendahara Umum)'), ('Organisasi', 'Organisasi'), ('Sosial', 'Sosial Pemberdayaan Masyarakat'), ('DPM', 'DPM'), ('Seni Budaya Olahraga', 'Seni Budaya Olahraga'), ('SBO', 'SBO'), ('IMMawati', 'IMMawati'), ('IMMawan', 'IMMawan'), ('Kader', 'KADER'), ('Kewirausahaan', 'Kewirausahaan dan Eksternal'), ('FAIKRIK', 'FAIKRIK'), ('KPPK', 'KPPK'), ('PKM', 'PKM'), ('Komunikasi', 'Komunikasi'), ('Tadbigh', 'Tadbigh'), ('BPK', 'BPK')], default='None', max_length=100, verbose_name='Bidang/Divisi'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='leadership_type',
            field=models.CharField(choices=[('KetuUm', 'Ketua Umum'), ('SekUm', 'Sekretaris Umum'), ('BendUm', 'Bendahara Umum'), ('KetuBid', 'Ketua Bidang'), ('SekBid', 'Sekretaris Bidang'), ('Anggota', 'Anggota Bidang'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=10, verbose_name='Jenis Kepemimpinan'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Centang jika anggota ini ingin ditampilkan.', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Urutan tampilan dalam satu kelompok/level. Angka lebih kecil tampil duluan.'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Jabatan Spesifik'),
        ),
    ]
