# Generated by Django 5.0.6 on 2025-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0008_alter_organizationmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='bio_or_description',
            field=models.TextField(blank=True, null=True, verbose_name='Biografi Singkat/Deskripsi Tugas'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='division',
            field=models.CharField(choices=[('None', 'None (Untuk Ketua/Sekum/Bendahara Umum)'), ('Kader', 'Kader'), ('Riset & Pengembangan Keilmuan', 'Riset & Pengembangan Keilmuan'), ('Media & Komunikasi', 'Media & Komunikasi'), ('Organisasi', 'Organisasi'), ('Hikmah, Politik, & Kebijakan Publik', 'Hikmah, Politik, dan Kebijakan Publik')], default='None', max_length=100, verbose_name='Bidang/Divisi'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Urutan tampilan dalam satu kelompok/level.'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Periode Jabatan'),
        ),
    ]
