# Generated by Django 5.0.6 on 2025-06-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0009_alter_organizationmember_bio_or_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='division',
            field=models.CharField(choices=[('None', 'None (Untuk Ketua/Sekum/Bendahara Umum)'), ('Kader', 'Kader'), ('Riset & Pengembangan Keilmuan', 'Riset & Pengembangan Keilmuan'), ('Media & Komunikasi', 'Media & Komunikasi'), ('Organisasi', 'Organisasi'), ('HPKP', 'HPKP')], default='None', max_length=100, verbose_name='Bidang/Divisi'),
        ),
    ]
