# Generated by Django 5.0.6 on 2025-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0011_alter_organizationmember_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='division',
            field=models.CharField(choices=[('None', 'None (Untuk Ketua/Sekum/Bendahara Umum)'), ('Organisasi', 'Bidang Organisasi'), ('Kaderisasi', 'Bidang Kaderisasi'), ('Riset & Pengembangan Keilmuan', 'Bidang Riset & Pengembangan Keilmuan'), ('Tablig, Kajian, & Keislaman', 'Bidang Tablig, Kajian, dan Keislaman'), ('Hikmah, Politik, & Kebijakan Publik', 'Bidang Hikmah, Politik, dan Kebijakan Publik'), ('Immawati', 'Bidang Immawati'), ('Media & Komunikasi', 'Bidang Media dan Komunikasi'), ('Sosial & Pemberdayaan Masyarakat', 'Bidang Sosial dan Pemberdayaan Masyarakat'), ('Lingkungan Hidup', 'Bidang Lingkungan Hidup'), ('Ekonomi & Kewirausahaan', 'Bidang Ekonomi dan Kewirausahaan'), ('Seni, Budaya, & Olahraga', 'Bidang Seni, Budaya, dan Olahraga')], default='None', max_length=100, verbose_name='Bidang/Divisi'),
        ),
    ]
