# Generated by Django 5.0.6 on 2025-06-30 15:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tampilanutama_app', '0012_alter_organizationmember_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sejarah IMM', max_length=200, verbose_name='Judul Halaman')),
                ('content', tinymce.models.HTMLField(verbose_name='Isi Halaman Sejarah')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diperbarui')),
            ],
            options={
                'verbose_name': 'Halaman Sejarah',
                'verbose_name_plural': 'Halaman Sejarah',
            },
        ),
    ]
