# Generated by Django 5.0.6 on 2025-06-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasisPengetahuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kriteria_nama', models.CharField(help_text="Nama kriteria, misal: 'Ada KTP', 'Ada Ijazah', 'Informasi Personal Lengkap'", max_length=255, unique=True)),
                ('pola_regex', models.TextField(blank=True, help_text="Pola Regex untuk mencari teks spesifik (misal: 'NIK: \\d{16}', 'Lulusan (S1|D3) Tahun \\d{4}').")),
                ('kata_kunci', models.TextField(blank=True, help_text="Kata kunci yang harus ada, pisahkan dengan koma (misal: 'nama lengkap, tanggal lahir, alamat').")),
                ('keterangan', models.TextField(blank=True, help_text='Deskripsi atau instruksi tambahan untuk AI.')),
                ('aktif', models.BooleanField(default=True, help_text='Apakah kriteria ini aktif digunakan?')),
            ],
            options={
                'verbose_name_plural': 'Basis Pengetahuan',
            },
        ),
        migrations.CreateModel(
            name='BerkasPendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pendaftar', models.CharField(max_length=255)),
                ('email_pendaftar', models.EmailField(max_length=255)),
                ('hasil_seleksi', models.JSONField(blank=True, null=True)),
                ('tanggal_unggah', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KonfigurasiUnggah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_pdfs', models.PositiveIntegerField(default=5, help_text='Jumlah maksimal file PDF yang bisa diunggah per pendaftaran.')),
                ('max_pdf_size_mb', models.PositiveIntegerField(default=10, help_text='Ukuran maksimal per file PDF dalam MB.')),
                ('max_photos', models.PositiveIntegerField(default=2, help_text='Jumlah maksimal pas foto yang bisa diunggah per pendaftaran.')),
                ('max_photo_size_mb', models.PositiveIntegerField(default=5, help_text='Ukuran maksimal per pas foto dalam MB.')),
            ],
            options={
                'verbose_name_plural': 'Konfigurasi Unggah',
            },
        ),
        migrations.CreateModel(
            name='PasFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(blank=True, max_length=255)),
                ('file', models.ImageField(upload_to='berkas_pendaftaran/pas_fotos/')),
                ('ukuran_asli', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='berkas_pendaftaran/pdfs/')),
                ('jenis_dokumen', models.CharField(blank=True, help_text='Contoh: KTP, Ijazah, Surat Lamaran', max_length=100, null=True)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_pdfs', to='pendaftaran_app.berkaspendaftaran')),
            ],
        ),
        migrations.AddConstraint(
            model_name='konfigurasiunggah',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_konfigurasi_unggah'),
        ),
        migrations.AddField(
            model_name='pasfoto',
            name='pendaftaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pas_fotos', to='pendaftaran_app.berkaspendaftaran'),
        ),
    ]
