# Generated by Django 5.0.6 on 2025-06-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basispengetahuan',
            options={'verbose_name': 'Field Ekstraksi AI', 'verbose_name_plural': 'Field Ekstraksi AI'},
        ),
        migrations.RemoveField(
            model_name='basispengetahuan',
            name='kata_kunci',
        ),
        migrations.RemoveField(
            model_name='basispengetahuan',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='basispengetahuan',
            name='kriteria_nama',
        ),
        migrations.RemoveField(
            model_name='basispengetahuan',
            name='pola_regex',
        ),
        migrations.AddField(
            model_name='basispengetahuan',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi detail untuk instruksi AI atau validasi tambahan.'),
        ),
        migrations.AddField(
            model_name='basispengetahuan',
            name='display_name',
            field=models.CharField(default='Default Display Name', help_text='Nama tampilan untuk field ini (misal: Nama Lengkap, Alamat Email)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basispengetahuan',
            name='expected_format_hint',
            field=models.TextField(blank=True, help_text="Petunjuk untuk AI tentang format yang diharapkan (misal: 'tanggal dengan format DD Bulan YYYY', 'email valid')"),
        ),
        migrations.AddField(
            model_name='basispengetahuan',
            name='field_name',
            field=models.CharField(default='default_field_name', help_text='Nama field yang akan diekstrak (misal: nama_lengkap, alamat_email, pengalaman_organisasi)', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basispengetahuan',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Apakah field ini wajib diisi?'),
        ),
        migrations.AlterField(
            model_name='basispengetahuan',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Apakah field ini aktif untuk diekstrak oleh AI?'),
        ),
        migrations.AlterField(
            model_name='filepdf',
            name='jenis_dokumen',
            field=models.CharField(blank=True, help_text='Contoh: Formulir Pendaftaran, Surat Pernyataan', max_length=100, null=True),
        ),
    ]
