# Generated by Django 5.2.1 on 2025-05-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nama singkat untuk aturan ini (misalnya, 'Tolak Topik Politik')", max_length=100, unique=True)),
                ('topic', models.CharField(help_text="Topik atau kata kunci yang diatur (misalnya, 'politik', 'harga saham X')", max_length=255)),
                ('allowed', models.BooleanField(default=True, help_text='Centang jika chatbot BOLEH membahas topik ini. Kosongkan jika TIDAK BOLEH.')),
                ('description', models.TextField(help_text="Deskripsi detail tentang aturan ini dan bagaimana chatbot harus merespons (misalnya, 'Jika ditanya tentang politik, jawab bahwa Anda tidak dapat membahas topik tersebut.')")),
                ('is_active', models.BooleanField(default=True, help_text='Aktifkan atau nonaktifkan aturan ini.')),
            ],
            options={
                'verbose_name': 'Aturan Chatbot',
                'verbose_name_plural': 'Aturan Chatbot',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text="Kata kunci utama untuk entri ini (misalnya, 'Jam Operasional', 'Harga Produk A')", max_length=100, unique=True)),
                ('information', models.TextField(help_text='Informasi detail yang harus diketahui chatbot terkait kata kunci ini.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Aktifkan atau nonaktifkan entri basis pengetahuan ini.')),
            ],
            options={
                'verbose_name': 'Entri Basis Pengetahuan',
                'verbose_name_plural': 'Entri Basis Pengetahuan',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_app.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
